#!/usr/bin/env python
from django.core.management import execute_manager
try:
    import commissioning.servers.quotaholder_django.settings as settings
except ImportError:
    import sys
    sys.stderr.write("%s: Can't import settings." % __file__)
    sys.exit(1)

if __name__ == "__main__":
    execute_manager(settings)
