snf-cyclades-gtools/conf/* etc/synnefo

snf-cyclades-gtools/collectd/plugins/ganeti-cpustats.py usr/lib/snf-cyclades-gtools/collectd
snf-cyclades-gtools/collectd/plugins/ganeti-netstats.py usr/lib/snf-cyclades-gtools/collectd
snf-cyclades-gtools/collectd/conf/ganeti-stats.conf etc/collectd
snf-cyclades-gtools/collectd/examples/ganeti-stats-collectd.conf usr/share/doc/snf-cyclades-gtools/examples
snf-cyclades-gtools/collectd/README.collectd usr/share/doc/snf-cyclades-gtools/
