#!/bin/sh
#
# This file is a shell script to be sourced by the appropriate 
# init.d script
#

VERBOSE=yes

# Run as a daemon? true/false
SNF_DSPTCH_ENABLE=true

# User to run the dispatcher as
SNF_USER="www-data"

# How many workers, default 2
WORKERS=2

SNF_DPTCH_OPTS="--workers=2"
