#!/usr/bin/env python
#
# Copyright (C) 2010-2014 GRNET S.A.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Invalid name for type module. pylint: disable-msg=C0103

"""
Continuous Integration script for Synnefo.
"""

import os
import sys
import utils
from optparse import OptionParser

CREATE_SERVER_CMD = "create"
DELETE_SERVER_CMD = "delete"
BUILD_SYNNEFO_CMD = "build"
BUILD_DOCS_SYNNEFO_CMD = "docs"
DEPLOY_SYNNEFO_CMD = "deploy"
TEST_SYNNEFO_CMD = "test"
RUN_BURNIN_CMD = "burnin"
CREATE_X2GO_FILE = "x2goplugin"
SHELL_CONNECT = "shell"
ALL_CMDS = "all"

DEFAULT_CONFIG_FILE = os.path.expanduser("~/.synnefo_ci")

COMMANDS_IN_ALL_MODE = [
    CREATE_SERVER_CMD,
    BUILD_SYNNEFO_CMD,
    BUILD_DOCS_SYNNEFO_CMD,
    DEPLOY_SYNNEFO_CMD,
    TEST_SYNNEFO_CMD,
    RUN_BURNIN_CMD,
]

AVAILABLE_COMMANDS = [
    CREATE_X2GO_FILE,
    DELETE_SERVER_CMD,
    SHELL_CONNECT,
] + COMMANDS_IN_ALL_MODE

USAGE = """usage: %%prog [options] command[,command...]

command:
    * %s: Create the slave server
    * %s: Create debian packages for Synnefo in the created server
    * %s: Create documentation for Synnefo in the created server
    * %s: Deploy Synnefo in created server
    * %s: Run Synnefo unittests
    * %s: Run snf-burnin in the deployed Synnefo
    * %s: Create x2go plugin file
    * %s: Delete the slave server
    * %s: Connect to the server using ssh

    * %s: Run all the available commands
""" % tuple([CREATE_SERVER_CMD,
             BUILD_SYNNEFO_CMD,
             BUILD_DOCS_SYNNEFO_CMD,
             DEPLOY_SYNNEFO_CMD,
             TEST_SYNNEFO_CMD,
             RUN_BURNIN_CMD,
             CREATE_X2GO_FILE,
             DELETE_SERVER_CMD,
             SHELL_CONNECT,
             ALL_CMDS])


def main():  # pylint: disable=too-many-statements, too-many-branches
    """Parse command line options and run the specified actions"""
    parser = OptionParser(usage=USAGE)
    parser.add_option("-c", "--conf", dest="config_file",
                      default=DEFAULT_CONFIG_FILE,
                      help="Configuration file for SynnefoCI"
                           " script (Default: %s)" % DEFAULT_CONFIG_FILE)
    parser.add_option("--cloud", dest="kamaki_cloud", default=None,
                      help="Use specified cloud, as is in .kamakirc")
    parser.add_option("--synnefo-repo", dest="synnefo_repo", default=None,
                      help="Specify the synnefo repo to use")
    parser.add_option("--synnefo-branch", dest="synnefo_branch", default=None,
                      help="Specify the synnefo branch to use")
    parser.add_option("--pull-request", dest="pull_request", default=None,
                      help="Test a Github pull request.")
    parser.add_option("-f", "--flavor", dest="flavor", default=None,
                      help="Flavor to use for the server."
                           " Supports both search by name (reg expression)"
                           " with \"name:flavor name\" or by id with"
                           " \"id:flavor id\".")
    parser.add_option("-i", "--image", dest="image", default=None,
                      help="Image to use for the server."
                           " Supports both search by name (reg expression)"
                           " with \"name:image name\" or by id with"
                           " \"id:image id\".")
    parser.add_option("--ssh-keys", dest="ssh_keys", default=None,
                      help="Upload/Install the public ssh keys contained"
                           " in this file to the server")
    parser.add_option("--local-package-dir", dest="local_package_dir",
                      default=None, help="Upload local packages from this dir "
                      "to the server")
    parser.add_option("--name", dest="server_name", default=None,
                      help="")
    parser.add_option("-n", "--build-id", dest="build_id", default=None,
                      type="int",
                      help="Specify a number to use to identify this build."
                           " One can later use this number to retrieve"
                           " information (such as IPs, passwords etc) about"
                           " the machines created. If not given this script"
                           " will create a new build-id.")
    parser.add_option("--fetch-packages", dest="fetch_packages",
                      default=None,
                      help="Download the debian packages that were created"
                           " during the '%s' step in this directory." %
                           BUILD_SYNNEFO_CMD)
    parser.add_option("--fetch-docs", dest="fetch_docs",
                      default=None,
                      help="Download the documentation that was created"
                           " during the '%s' step in this directory." %
                           BUILD_DOCS_SYNNEFO_CMD)
    parser.add_option("--schema", dest="schema", default=None,
                      help="Schema for snf-deploy.")
    parser.add_option("--local-repo", dest="local_repo", default=False,
                      action="store_true",
                      help="Instead of cloning from the official Synnefo"
                           " repo, copy and use the local one.")
    parser.add_option("--x2go-output", dest="x2go_output", default=None,
                      help="File where to save the x2go plugin html page.")
    parser.add_option("--no-colors", dest="use_colors",
                      default=True, action="store_false",
                      help="Don't use colorful output messages.")
    parser.add_option("--ignore-ssl", "-k", dest="ignore_ssl",
                      default=None, action="store_true",
                      help="Don't verify SSL certificates.")

    (options, args) = parser.parse_args()

    # ----------------------------------
    # Check arguments
    if len(args) != 1:
        msg = "ERROR: Command takes exactly one argument"
        parser.print_help()
        print
        print msg
        return

    commands = args[0]
    if commands == ALL_CMDS:
        for cmd in COMMANDS_IN_ALL_MODE:
            setattr(options, cmd, True)

    else:
        commands = commands.split(",")
        for command in commands:
            if command not in AVAILABLE_COMMANDS:
                msg = "ERROR: Unknown command: %s" % command
                parser.print_help()
                print
                print msg
                sys.exit(1)
            else:
                setattr(options, command, True)

    if options.pull_request is not None:
        if (options.synnefo_repo is not None or
                options.synnefo_branch is not None):
            print "ERROR: Options 'synnefo_repo' and/or 'synnefo_branch'" \
                " cannot be given with 'pull_request'"
            sys.exit(1)

    # ----------------------------------
    # Initialize SynnefoCi
    utils.USE_COLORS = options.use_colors
    utils.IGNORE_SSL = options.ignore_ssl
    config_file = options.config_file
    if config_file is not None:
        config_file = os.path.expanduser(config_file)
        if not os.path.exists(config_file):
            print "Configuration file '%s' does not exist!" % config_file
            config_file = None
    synnefo_ci = utils.SynnefoCI(config_file=config_file,
                                 build_id=options.build_id,
                                 cloud=options.kamaki_cloud)

    # ----------------------------------
    # Run commands
    if getattr(options, CREATE_SERVER_CMD, False):
        synnefo_ci.create_server(flavor=options.flavor,
                                 image=options.image,
                                 ssh_keys=options.ssh_keys,
                                 server_name=options.server_name)
        synnefo_ci.clone_repo(
            synnefo_repo=options.synnefo_repo,
            synnefo_branch=options.synnefo_branch,
            local_repo=options.local_repo,
            pull_request=options.pull_request)
    if getattr(options, BUILD_SYNNEFO_CMD, False):
        synnefo_ci.build_packages()
        if options.fetch_packages:
            dest = os.path.abspath(options.fetch_packages)
            synnefo_ci.fetch_packages(dest=dest)
    if getattr(options, BUILD_DOCS_SYNNEFO_CMD, False):
        synnefo_ci.build_documentation()
        if options.fetch_docs:
            dest = os.path.abspath(options.fetch_docs)
            synnefo_ci.fetch_documentation(dest=dest)
    if getattr(options, DEPLOY_SYNNEFO_CMD, False):
        synnefo_ci.deploy_synnefo(schema=options.schema,
                                  local_package_dir=options.local_package_dir)
    if getattr(options, TEST_SYNNEFO_CMD, False):
        synnefo_ci.unit_test()
    if getattr(options, RUN_BURNIN_CMD, False):
        synnefo_ci.run_burnin()
    if getattr(options, CREATE_X2GO_FILE, False):
        synnefo_ci.x2go_plugin(options.x2go_output)
    if getattr(options, DELETE_SERVER_CMD, False):
        synnefo_ci.destroy_server()
    if getattr(options, SHELL_CONNECT, False):
        synnefo_ci.shell_connect()


if __name__ == "__main__":
    main()
