#!/usr/bin/env python
from commissioning.lib.http import main, HTTP_API_Client
from quotaholder.api import QuotaholderAPI


class QuotaholderHTTP(HTTP_API_Client):
    api_spec = QuotaholderAPI()


if __name__ == '__main__':
    main()

