#!/usr/bin/env python
from os import environ
settings_name = 'quotaholder.servers.quotaholder_django.settings'
environ['DJANGO_SETTINGS_MODULE'] = settings_name

from django.utils.importlib import import_module
from django.core.management import execute_manager
try:
    settings = import_module(settings_name)
except ImportError, e:
    import sys
    sys.stderr.write("%s: Can't import settings from %s: %s.\n"
                                    % (__file__, settings_name, e))
    sys.exit(1)

if __name__ == "__main__":
    execute_manager(settings)
