#!/usr/bin/env python
from os import environ
from os.path import basename
from sys import argv


environ['COMMISSIONING_APP_NAME'] = 'fscrud'

from django.core.management import execute_manager
try:
    import commissioning.servers.fscrud.settings as settings
except ImportError:
    import sys
    sys.stderr.write("%s: Can't import settings." % __file__)
    sys.exit(1)

if __name__ == "__main__":
    execute_manager(settings)
