#!/usr/bin/env python

from util import *

from httplib import HTTPConnection
from optparse import OptionParser
from sys import exit

import json

parser = OptionParser(add_help_option=True)
parser.add_option('-s', dest='host', metavar='HOST', default=DEFAULT_HOST,
                    help='use server HOST')
parser.add_option('-a', dest='api', metavar='API', default=DEFAULT_API,
                    help='use api API')
parser.add_option('-f', dest='flavor', metavar='FLAVOR_ID', default=1,
                    help='Flavor ID')
parser.add_option('-i', dest='image', metavar='IMAGE_ID', default=1,
                    help='Image ID')

options, args = parser.parse_args()

conn = HTTPConnection(options.host)

path = '/api/%s/servers' % options.api
name = args[0]
server = dict(name=args[0], flavorId=options.flavor, imageId=options.image)
body = json.dumps({'server': server})
headers = {'Content-Type': 'application/json'}

conn.request('POST', path, body, headers)
resp = conn.getresponse()

if resp.status != 202:
    print 'Error:', resp.status
    exit(1)

buf = resp.read()
reply = json.loads(buf)
    
server = reply['server']
server.pop('id')
print_server(server)
