#!/usr/bin/env python

from util import *

from httplib import HTTPConnection
from optparse import OptionParser
from sys import exit

import json

parser = OptionParser(add_help_option=True)
parser.add_option('-s', dest='host', metavar='HOST', default=DEFAULT_HOST,
                    help='use server HOST')
parser.add_option('-a', dest='api', metavar='API', default=DEFAULT_API,
                    help='use api API')
parser.add_option('-l',  action='store_true', dest='detail', default=False,
                    help='show detailed output')

options, args = parser.parse_args()

conn = HTTPConnection(options.host)

path = '/api/%s/servers' % options.api
if options.detail:
    path += '/detail'

conn.request('GET', path)
resp = conn.getresponse()

if resp.status != 200:
    print 'Error:', resp.status
    exit(1)

buf = resp.read()
reply = json.loads(buf)

for server in reply['servers']['values']:
    id = server.pop('id')
    name = server.pop('name')
    if options.detail:
        print '%d %s' % (id, name)
        print_server(server)
        print
    else:
        print '%3d %s' % (id, name)
