#!/usr/bin/env python

# Copyright 2011 GRNET S.A. All rights reserved.
# 
# Redistribution and use in source and binary forms, with or
# without modification, are permitted provided that the following
# conditions are met:
# 
#   1. Redistributions of source code must retain the above
#      copyright notice, this list of conditions and the following
#      disclaimer.
# 
#   2. Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials
#      provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY GRNET S.A. ``AS IS'' AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL GRNET S.A OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
# USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
# AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
# 
# The views and conclusions contained in the software and
# documentation are those of the authors and should not be
# interpreted as representing official policies, either expressed
# or implied, of GRNET S.A.

from lib.migrate import Migration

from sqlalchemy import Table
from pithos.aai.models import PithosUser

import base64

class UserMigration(Migration):
    def __init__(self, db):
        Migration.__init__(self, db)
        self.gss_users = Table('gss_user', self.metadata, autoload=True)
    
    def execute(self):
        s = self.gss_users.select()
        users = self.conn.execute(s).fetchall()
        l = []
        for u in users:
            user = PithosUser()
            user.pk = u['id']
            user.uniq = u['username']
            user.realname = u['name']
            user.is_admin = False
            user.affiliation = u['homeorganization'] if u['homeorganization'] else ''
            user.auth_token = base64.b64encode(u['authtoken'])
            user.auth_token_created = u['creationdate']
            user.auth_token_expires = u['authtokenexpirydate']
            user.created = u['creationdate']
            user.updated = u['modificationdate']
            print '#', user
            user.save(update_timestamps=False)

if __name__ == "__main__":
    db = 'postgresql://gss:m0ust@rda@62.217.112.56/pithos'
    m = UserMigration(db)
    m.execute()