#!/usr/bin/env python

import sys
import os

from lib.client import Pithos_Client
from lib.util import get_user, get_auth, get_server, get_api
from lib.transfer import smart_upload

# XXX Get these from container...
BLOCK_SIZE = 4 * 1024 * 1024
BLOCK_HASH = 'sha256'

if __name__ == '__main__':
    if len(sys.argv) != 2 or not os.path.isfile(sys.argv[1]):
        print 'syntax: %s <file>' % sys.argv[0]
        sys.exit(1)
    
    client = Pithos_Client(get_server(), get_auth(), get_user())
    smart_upload(client, sys.argv[1], BLOCK_SIZE, BLOCK_HASH)
