#!/usr/bin/env python

from util import *

from httplib import HTTPConnection
from optparse import OptionParser
from sys import exit

import json

parser = OptionParser(add_help_option=True)
parser.add_option('-s', dest='host', metavar='HOST', default=DEFAULT_HOST,
                    help='use server HOST')
parser.add_option('-a', dest='api', metavar='API', default=DEFAULT_API,
                    help='use api API')

options, args = parser.parse_args()

conn = HTTPConnection(options.host)

path = '/api/%s/servers/%d' % (options.api, int(args[0]))
name = args[1]
body = json.dumps({'server': {'name' : name}})
headers = {'Content-Type': 'application/json'}

conn.request('PUT', path, body, headers)
resp = conn.getresponse()

if resp.status != 204:
    print 'Error:', resp.status
    exit(1)
